### ISSUE TITLE
Differences between django-behave?

### ISSUE THREAD

**Issue by nikolas** [mixxorz/behave-django#13]
Is there any reason I should use this library instead of [django-behave](https://github.com/django-behave/django-behave), which I'm currently using?

**Comment by nikolas** [comment]
Nevermind, I see the differences summarized here: https://github.com/behave/behave/pull/321/files

**Comment by bittner** [comment]
Awesome, thank you! :+1: for referencing the pull request on the [behave documentation](https://github.com/behave/behave/blob/master/docs/django.rst).  :smirk:
It will be in the official documentation [[1]](http://pythonhosted.org/behave/django.html) with their next release.
