### ISSUE TITLE
CI fails mysteriously with Django 1.6

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/behave-django#14]
It has something to do with redirecting to `/dev/null` apparently.

**Comment by bittner** [comment]
As mentioned in pull request #12, the Python 2.6 + Django 1.6 problem may have been a Travis-CI issue. They had some [infrastructure issues](https://www.traviscistatus.com/) today and probably changed stuff. Note, for example, that [build #51](https://travis-ci.org/mixxorz/behave-django/builds/65257416) of the PR had passed for the 2.6/1.6 combination, although the `/dev/null` redirection had been restored to an earlier state (that had failed earlier).

**Comment by mixxorz** [comment]
I see! I'll keep this open just in case. We'll see in the next few days.

**Comment by bittner** [comment]
Very strange, now the build seems to
- work for Python 2.6 + Django 1.6 (failed in [build 53](https://travis-ci.org/mixxorz/behave-django/builds/65356834)) and
- fail for Python 2.7 + Django 1.6! (worked in build 53)

See Travis-CI [build 54](https://travis-ci.org/mixxorz/behave-django/builds/65431637).

**Comment by mixxorz** [comment]
Yep. and I can't reproduce this on my local machine. Same Python version, same Django version. :sob:

**Comment by mixxorz** [comment]
Aaand it passes this time. [Build #57](https://travis-ci.org/mixxorz/behave-django/builds/65884827). This is looking more and more like a non-issue.

**Comment by mixxorz** [comment]
It doesn't happen anymore...?
