### ISSUE TITLE
Update method of testing behave-django on CI

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/behave-django#15]
Some features of `behave-django` are not available to Django < 1.5. As such, there should be a way of skipping expected-to-fail-tests on particular Django/Python version combinations on the CI.

The proposed solution is to write a test script (`test.sh`) that will be called by the CI instead of calling `python manage.py behave --tags ~@skip && python tests.py`. By doing so, we will be given access to the testing environment variables which can help in modifying which tests run on which Django/Python combo.

**Comment by bittner** [comment]
Note that the changes of PR #12 now also work for Django < 1.5, hence the test matrix can stay as it is today. At least for this specific contribution.

**Comment by mixxorz** [comment]
I don't think we need this anymore
