### ISSUE TITLE
Move documentation from Wiki to a docs folder in the project repo

### ISSUE THREAD

**Issue by bittner** [mixxorz/behave-django#16]
As of today, the documentation is in the repository's Wiki. It should be moved to a docs folder in the project repository and converted to reStructuredText. This way pull requests can include changes to the documentation that reflect the changes made to the source code.

Things to do afterwards:
- Move some docstrings from the source to the documentation (e.g. from [get_url](https://github.com/mixxorz/behave-django/pull/12/files#diff-3fd86c37800e90054aa0f6b2b57a0822R27)) to make sure there is only one place to update the description of the current behavior
- Script and/or automate the generation of the docs
- Upload the generated documentation to pythonhosted.org (PyPI) or readthedocs.org
- Update README and setup.py to make sure the PyPI package reflects the new location of the docs
- Maybe add a hint or redirect on the Wiki to tell visitors where the former docs have gone

**Comment by nikolas** [comment]
I agree! It would be great to get this documentation into the docs/ dir and up on readthedocs.org. Then I could submit pull requests for the documentation. For example, I'd like to add a note about how to integrate splinter with behave-django. The current getting started page on the wiki mentions this but doesn't go into depth.

**Comment by mixxorz** [comment]
When I started this project, I thought I'd be easier to just use the Wiki. But I guess using Sphinx or readthedocs would be better. I've never tried it before though. :stuck_out_tongue:

**Comment by mixxorz** [comment]
This is implemented by #20. Docs are now at [pythonhosted.org](https://pythonhosted.org/behave-django/)
