### ISSUE TITLE
Running specific scenario of a feature file

### ISSUE THREAD

**Issue by nikolas** [mixxorz/behave-django#21]
In lettuce, you can specify which feature file to run, and further narrow it down by scenario:
http://lettuce.it/reference/cli.html#lettuce-running-only-some-scenarios-all-feature-files

Is this currently possible in behave-django? It's an important feature, and I'd like to document it if it's already built in.

As far as I know, this isn't possible in django-behave. See: https://github.com/django-behave/django-behave/issues/58

**Comment by nikolas** [comment]
Well, I figured out how to run a specific file! This works: `./manage.py behave features/index.feature`

**Comment by mixxorz** [comment]
Yep! Just a reminder that you can use _any_ behave command line option with `python manage.py behave`. And yes this includes specifying specific feature files.
