### ISSUE TITLE
switch from optparse to argparse

### ISSUE THREAD

**Issue by nikolas** [mixxorz/behave-django#24]
I noticed `behave.py` uses `optparse`.. I think we should switch to `argparse` as it's better supported.

From https://docs.python.org/2/library/optparse.html

> Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

I'll try to make a PR for this at some point, unless you get to it before I do.

**Comment by bittner** [comment]
@nikolas, just a few hints to get you started, if you don't mind:
- <s>Be inspired by [code I wrote for django-organice](https://github.com/Organice/django-organice/blob/develop/organice/bin/organice_setup.py#L91) (saves you some trouble-shooting) ...</s> **(EDIT, 2016/02: obsolete in the meantime)**
- ... though a `try`-`except` approach may be more pythonic, e.g.

``` python
try:
    from argparse import ArgumentParser  # New since Python 2.7
    parser = ArgumentParser()
except ImportError:
    from optparse import OptionParser  # Deprecated since Python 2.7
    parser = OptionParser()
    parser.add_argument = parser.add_option  # use add_argument in any case

parser.add_argument('foo', help='foo does bar and baz')

# ... and a similar try-except block for the actual parsing and evaluation
```

**Comment by nikolas** [comment]
@bittner thanks for the tips!

**Comment by bittner** [comment]
Another note: I just see, until Django 1.7 optparse's `make_option` is used for the `option_list`. The implementation of our management command pretty much depends on that. Django 1.8 makes the switch finally to argparse. I fear an implementation change on our side will probably have to follow their approach and may need to consider the Django version in use.

## See Also
- https://github.com/django/django/blob/1.7/django/core/management/base.py#L184
- https://github.com/django/django/blob/1.8/django/core/management/base.py#L224
- [Python optparse make_option() equivalent in argparse](http://stackoverflow.com/questions/14387540/python-optparse-make-option-equivalent-in-argparse) (StackOverflow)

**Comment by oiwn** [comment]
This deprecation warning is a bit annoying. Any news?

**Comment by bittner** [comment]
This affects
- [behave_django/parser.py](https://github.com/mixxorz/behave-django/blob/master/behave_django/parser.py#L1)
- [behave_django/management/commands/behave.py](https://github.com/mixxorz/behave-django/blob/master/behave_django/management/commands/behave.py#L2)

Anything else?

What is the exact deprecation warning, and when does it occur? (I don't notice any with Python 3.4 and Django 1.8)

**Comment by bittner** [comment]
@mixxorz We should address this deprecation warning now that we're under the hood of  the `behave` organization. As more and more developers start using Django 1.9 this issue becomes more visible.

**Comment by bittner** [comment]
Closing this issue in favor of [issue 2](https://github.com/behave/behave-django/issues/2) in `behave/behave-django`. Please follow-up there.
