### ISSUE TITLE
PyPi readme is broken

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/behave-django#32]
This was caused by incompatible reStructuredText in README.rst. Minor issue. Will be fixed in the next release.

**Comment by mixxorz** [comment]
It's still broken. Is there any way to test if pypi will parse the README?

**Comment by mixxorz** [comment]
I got it. You can use `python setup.py check -s --restructuredtext` to check for any rst issues. I promise it will work next release. :laughing:

**Comment by bittner** [comment]
How about integrating this test along with flake8 in our test suite?

The broken README on PyPI is sooo common, we shouldn't allow this to come back ever again.

**Comment by mixxorz** [comment]
I tried! I opened a PR a few days ago. #35 But that came with its own set of problems like the CI not having docutils and Python 2.6 compatibility issues and ugh. I realized that I'm really the only one who has to worry about this anyway, so I'll just do it manually lol.

**Comment by bittner** [comment]
The tool PyPI is using to convert the `long_description` into HTML is `rst2html`. A proper check/test should probably use it directly.

See also: https://docs.python.org/2/distutils/packageindex.html#pypi-package-display

**Comment by bittner** [comment]
Actually, your option works better. Weird that it's not mentioned in the Python docs... :confused:

**Comment by mixxorz** [comment]
It's fixed finally.
