### ISSUE TITLE
Setup instructions on PyPI still list code to add in `environment.py`

### ISSUE THREAD

**Issue by bittner** [mixxorz/behave-django#38]
Interestingly, the setup instructions of [version 0.2.2 on PyPI](https://pypi.python.org/pypi/behave-django) still list the old setup procedure, requiring to add code to `environment.py`.

Instead, this should match the setup instructions of the [package documentation](https://pythonhosted.org/behave-django/installation.html).

**Comment by bittner** [comment]
Ah, this is fixed by commit [8ac388c](https://github.com/mixxorz/behave-django/commit/8ac388c0537ef9bb1ab224595f24fd05a6e8fd89). Terrific!

**Comment by mixxorz** [comment]
Yeah this should reflect on the next update. :+1:
