### ISSUE TITLE
You should be able to pass --keepdb

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/behave-django#44]
Django's testing suite has an option to pass `--keepdb` to avoid having to create and destroy the test database between each test run. You should be able to use `python manage.py behave --keepdb` to utilize this functionality.

**Comment by matejkloska** [comment]
Without this feature I cannot you this package. Migrations are terribly slow :/

**Comment by mixxorz** [comment]
Exactly why I brought it up. I'll probably work on it this weekend, unless someone beats me to it. :stuck_out_tongue:
