### ISSUE TITLE
Support for trailing `:` in steps

### ISSUE THREAD

**Issue by Goutte** [mixxorz/behave-django#49]
Say I write a step like this :

``` gherkin
Given there is this user :
"""
username: Bender
password: (\/) (;,,;) (\/)
email: 2716057@robots.mom
"""
```

_(because yeah, deep down, Bender is rooting for Zoidberg)_

And define it like this :

``` python
@Given(u"there is this user :")
def there_is_this_user(context):
    # do stuff with context.text in YAML format
```

The trailing `:` screws up matching !
I **have to** define it like this, **with a trailing space** :

``` python
@Given(u"there is this user ")
```

Maybe it's a `behave` issue, not a `behave-django` issue, but I don't know the codebases.
Can you help me ?

_I know I can easily go around this problem by using the regex parser instead, but I'm trying to teach BDD to people that don't know first thing about regexes and we all need them to learn BDD fast._

**Comment by mixxorz** [comment]
This is most definitely a `behave` issue. `behave-django` just makes the two work well together. It doesn't contain any of the parsing logic.
