### ISSUE TITLE
Add behave-django to awesome-django list

### ISSUE THREAD

**Issue by bittner** [mixxorz/behave-django#50]
behave-django should be added to the [Testing section](http://awesome-django.com/#awesome-django-testing) of Roberto Rosario's [awesome-django](https://gitlab.com/rosarior/awesome-django) list.

(Just to get this off my chest)

Maybe you have a "marketing" label for that.  :smirk:

**Comment by mixxorz** [comment]
Oh cool. I'll go ahead and do this.

**Comment by bittner** [comment]
This issue has been [resolved 10 days ago](https://gitlab.com/rosarior/awesome-django/merge_requests/2).

**Comment by mixxorz** [comment]
Thanks. :+1:
