### ISSUE TITLE
Support Python 3.5, refactor tox.ini

### ISSUE THREAD

**Issue by bittner** [mixxorz/behave-django#53]
## Add Python 3.5 to test matrix

Currently, our tests don't cover Python 3.5. Django 1.9 officially supports Python 3.5, and we test Django 1.9 in `tox.ini` and `.travis.yml`, so we should test with Python 3.5 and supported Django versions too.

Note that in Travis CI you have to use `python: 3.5` to specify the image you run the tests on. Otherwise `python3.5` will not be available (yet). See [this comment](https://github.com/jcassee/django-analytical/pull/73#issuecomment-162206854) for more information.

`.travis.yml` has to be updated accordingly.
## Refactor tox.ini

The definition of `basepython = py26 ...` is redundant. This is provided by tox by default, and can be omitted.

**Comment by mixxorz** [comment]
Closed by #56 

Except for the basepython thing. I'm fine with removing `basepython`. My only (probably unfounded) concern is that it's more explicit this way.
